;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-advanced-reader.ss" "lang")((modname ex14.4.4) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #t #t none #f () #f)))
(define-struct add (left right))
(define-struct mul (left right))

; 1. (+ 10 -10)
(define S1 (make-add 10 -10))
; 2. (+ (* 20 3) 33)
(define S2 (make-add (make-mul 20 3) 33))
; 3. (* 3.14 (* r r))
(define S3 (make-mul 3.14 (make-mul 'r 'r)))
; 4. (+ (* 9/5 c) 32)
(define S4 (make-add (make-mul 9/5 'c) 32))
; 5. (+ (* 3.14 (* o o)) (* 3.14 (* i i)))
(define S5 (make-add (make-mul 3.14 (make-mul 'o 'o)) (make-mul 3.14 (make-mul 'i 'i))))

;; subst : symbol number sch-exp -> sch-exp
;; substitutes variable with given value
(check-expect (subst 'r 2 S1) (make-add 10 -10))
(check-expect (subst 'r 2 S2) (make-add (make-mul 20 3) 33))
(check-expect (subst 'r 2 S3) (make-mul 3.14 (make-mul 2 2)))
(check-expect (subst 'c 5 S4) (make-add (make-mul 9/5 5) 32))
(check-expect (subst 'o 2 S5)
              (make-add (make-mul 3.14 (make-mul 2 2))
                        (make-mul 3.14 (make-mul 'i 'i))))
(check-expect (subst 'i 7 S5)
              (make-add (make-mul 3.14 (make-mul 'o 'o))
                        (make-mul 3.14 (make-mul 7 7))))
(check-expect (subst 'i 7 (subst 'o 2 S5))
              (make-add (make-mul 3.14 (make-mul 2 2))
                        (make-mul 3.14 (make-mul 7 7))))

(define (subst v n sch-exp)
  (cond ((and (symbol? sch-exp) (symbol=? v sch-exp)) n)
        ((number? sch-exp) sch-exp)
        ((and (add? sch-exp)
              (not (numeric? (add-left sch-exp)))
              (not (numeric? (add-right sch-exp))))
         (make-add (subst v n (add-left sch-exp))
                   (subst v n (add-right sch-exp))))
        ((and (add? sch-exp)
              (not (numeric? (add-left sch-exp))))
         (make-add (subst v n (add-left sch-exp)) (add-right sch-exp)))
        ((and (add? sch-exp)
              (not (numeric? (add-right sch-exp))))
         (make-add (add-left sch-exp) (subst v n (add-right sch-exp))))
        ((and (mul? sch-exp)
              (not (numeric? (mul-left sch-exp)))
              (not (numeric? (mul-right sch-exp))))
         (make-mul (subst v n (mul-left sch-exp))
                   (subst v n (mul-right sch-exp))))
        ((and (mul? sch-exp)
              (not (numeric? (mul-left sch-exp))))
         (make-mul (subst v n (mul-left sch-exp)) (mul-right sch-exp)))
        ((and (mul? sch-exp)
              (not (numeric? (mul-right sch-exp))))
         (make-mul (mul-left sch-exp) (subst v n (mul-right sch-exp))))
        (else sch-exp)))

(define (numeric? sch-exp)
  (cond ((number? sch-exp) #t)
        ((add? sch-exp) (and (numeric? (add-left sch-exp))
                             (numeric? (add-right sch-exp))))
        ((mul? sch-exp) (and (numeric? (mul-left sch-exp))
                             (numeric? (mul-right sch-exp))))
        (else #f)))